### PR TITLE
updating tokens and standarize names

### PR DESCRIPTION
**Pull request by alvaro-ricotta**
1. The names of the icons have been updated to their respective symbols.
2. All icons have been converted to SVG.

### CODE REVIEW

**Comment by alvaro-ricotta** [comment]
Validation of logoURI will fail first time, cuz we're requesting new icons from a repository and those icons doesn't exist yet

**Review by souradeep-das — APPROVED** [review]

**Comment by souradeep-das** [comment]
validation of logo should pass- because validation logic uses files from current branch

**Comment by souradeep-das** [comment]
also please update your branch to latest!

**Review by sk-enya — APPROVED** [review]
looks good!

**Pull request merged**
